### ISSUE TITLE
Debug test using specific tag

### ISSUE THREAD

**Issue by timofurrer** [leoluz/nvim-dap-go#36]
What's the best way to start debugging a test or file and use a specific `-tags=...` configuration?

I tried adding another `dap_configurations` or use the one which allows to specify arguments, but that doesn't help, because the `go test` command already fails.

**Comment by leoluz** [comment]
Can you pls clarify what are the `-tags=...` configuration that you are referring to exactly?

**Comment by timofurrer** [comment]
I meant when my project requires to be built with certain tags. In my case the acceptance test suite is marked with a specific tag. Thus,  I'm looking for an easy way to configure only that workspace to use this tag when running the tests.

**Comment by debugloop** [comment]
I'm facing the same issue. If unit tests are written with a build tag (i.e. `// +build unit`) excluding them from the regular build no binary can be produced.

Right now, there is no way to specify extra arts (i.e. `-tags=unit`) for dlv, but I think one can easily add them to config and use them [here](https://github.com/leoluz/nvim-dap-go/blob/b4ded7de579b4e2a85c203388233b54bf1028816/lua/dap-go.lua#L67). I can create a PR later on, right now I'm just deleting the tag temporarily when debugging. This is also the root cause of #35 I think (@Karmenzind).

**Comment by leoluz** [comment]
The plugin now permits to specify build flags that are passed to delve in the `setup()` function
Example:
```lua
require('dap-go').setup {
  delve = {
    build_flags = "-tags=unit",
  },
}
```
