### ISSUE TITLE
Debug root package

### ISSUE THREAD

**Issue by Jomik** [leoluz/nvim-dap-go#58]
I am unsure if I am doing something wrong here..
Currently when I try to run `continue` and just `Debug`, it will try to execute the current package.
This often fails, as the package would not have a main and thus not be executable.

Is it possible to somehow specify that a configuration that tries to debug the root package of the project, rather than the currently open file?

**Comment by leoluz** [comment]
> I am unsure if I am doing something wrong here..

Hey! no problem.. I don't understand exactly what you are doing. When you start the debug session, which option you select from the list? Check the documentation that you can pass the `build_flags`. Maybe you can use that to specify the root of your project.

**Comment by Jomik** [comment]
I simply choose `Debug`.
I assume that results in it trying to run the package I am in, but that is not executable.
So I need it to use the root from `gopls` 🤔 

If that is out of scope, that is understandable - as I said, may be my setup. Can you confirm you have the same happen to you?
I can create a small reproduction if needed?

**Comment by Jomik** [comment]
Still an issue.

**Comment by tehaleph** [comment]
Hi, @Jomik! I recently faced the same issue as you did. You are absolutely correct that the `Debug` option attempts to run the current file. This occurs because the DAP configuration uses the `${file}` [placeholder](https://github.com/leoluz/nvim-dap-go/blob/main/lua/dap-go.lua#L71).

However, we have several other [options](https://github.com/mfussenegger/nvim-dap/blob/405df1dcc2e395ab5173a9c3d00e03942c023074/doc/dap.txt#L303-L313) available that we can use to customize DAP configuration.

As an example, here's my configuration that runs `/cmd/main.go` from any file within the project:

```lua
require("dap-go").setup({
	dap_configurations = {
		{
			type = "go",
			name = "Debug main.go",
			request = "launch",
			program = "${workspaceFolder}/cmd/main.go"
		},
	}
})
```

I hope this helps!

**Comment by leoluz** [comment]
Tks @tehaleph for chiming in!
@Jomik feel free to reopen if you still have an issue
